Repository haynakoban/ipt2-case-study-MT, pull requests merged in 2022-10, with the labels that each got.

#1 Bryan webpage
  assets/JavaScript-logo.png
  assets/bg-image.png
  assets/ccs_banbanban.jpg
  assets/cj-dayrit-xX2aYSBsyKo-unsplash.jpg
  assets/css-logo.png
  assets/html-logo.svg
  assets/jpcs logo.png
  assets/logo.png
  assets/mysql-5-logo-png-transparent.png
  assets/nodejs-1-logo.png
  assets/progden logo.png
  assets/react-logo.png
  bryan/bryan.html
  bryan/script.js
  bryan/style.css
Labels: documentation, enhancement, help wanted

#5 Rizza webpage
  assets/rizza.jpg
  rizza/rizza.html
  rizza/script.js
  rizza/style.css
Labels: enhancement

#7 Theawebpage
  assets/IMG_20220105_145847_338.jpg
  index.html
  thea/script.js
  thea/style.css
  thea/thea.html
Labels: documentation, enhancement
